apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-security-config
data:
  CALDERA_API_KEY: your_caldera_api_key
  CALDERA_ENDPOINT: http://caldera-service:8888
  CLIP_MODEL: ViT-B/32
  CLIP_THRESHOLD: "0.85"
  DEEPEXPLOIT_SCAN_INTERVAL: "3600"
  DEEPEXPLOIT_TARGET_NETWORK: 10.0.0.0/24
  AIHIDS_LOG_PATH: /var/log/aihids
  AIHIDS_ALERT_THRESHOLD: "5"
  TF_PRIVACY_EPSILON: "1.0"
  TF_PRIVACY_DELTA: 1e-5
  AIRGAP_MODE: "true"
  LOCAL_REGISTRY: "registry.local:5000"
  NETWORK_ISOLATION: "strict"
  YGGDRASIL_ENABLED: "true"
  YGGDRASIL_PEERS: "tcp://peer1.local:12345,tcp://peer2.local:12345"
  YGGDRASIL_ENCRYPTION: "aes-256-gcm"
