apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caldera
  template:
    metadata:
      labels:
        app: caldera
    spec:
      containers:
      - name: caldera
        image: caldera:latest
        ports:
        - containerPort: 8888
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: caldera-service
spec:
  selector:
    app: caldera
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
