apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip
  template:
    metadata:
      labels:
        app: clip
    spec:
      containers:
      - name: clip
        image: clip:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: ai-security-config
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: clip-service
spec:
  selector:
    app: clip
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
