apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepexploit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepexploit
  template:
    metadata:
      labels:
        app: deepexploit
    spec:
      containers:
      - name: deepexploit
        image: deepexploit:latest
        ports:
        - containerPort: 55553
        envFrom:
        - configMapRef:
            name: ai-security-config
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: deepexploit-service
spec:
  selector:
    app: deepexploit
  ports:
  - protocol: TCP
    port: 55553
    targetPort: 55553
  type: ClusterIP
