apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepexploit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepexploit
  template:
    metadata:
      labels:
        app: deepexploit
    spec:
      containers:
      - name: deepexploit
        image: deepexploit:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: ai-security-config
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: deepexploit-service
spec:
  selector:
    app: deepexploit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
