apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
controllerManager:
  extraArgs:
    cluster-signing-duration: 87600h0m0s
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
    port: 10251
    secure-port: 10259
    leader-elect: true
    profiler: false
    kubeconfig: /etc/kubernetes/scheduler.conf
    tls-cert-file: /etc/kubernetes/pki/scheduler.crt
    tls-private-key-file: /etc/kubernetes/pki/scheduler.key
