apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetracryptpqc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetracryptpqc
  template:
    metadata:
      labels:
        app: tetracryptpqc
    spec:
      containers:
        - name: tetracryptpqc
          image: ghcr.io/baramaystation/tetracryptpqc:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
